### ISSUE TITLE
NaCl (Ed25519) signatures rely on Sodium for Swift 1.1, but no Sodium tag for that

### ISSUE THREAD

**Issue by stannie** [stannie/swift-jwt#3]
The Ed25519 signature uses Sodium framework, the swift wrapper of LibSodium, a NaCl implementation https://github.com/jedisct1/swift-sodium 
As the current version of Sodium is ported to Swift 1.2, I used the version right before that:
git checkout 176033d7c1cbc4dfe4bed648aa230c9e14ab9426 
Unfortunately there is no (release) tag for that

**Comment by stannie** [comment]
This issue also prevents me to add a dependency in the podspec file...

**Comment by jedisct1** [comment]
If this is a showstopper, I can definitely add a tag.

**Comment by stannie** [comment]
Thanks @jedisct1 ; I'm moving to Swift 1.2 with this project too, now that Apple released Xcode 6.3 last week, so it will be solved that way.  Would be great if you could add a Cocoapod (https://cocoapods.org) spec file though. I believe @ziogaschr will send you a pull request for that.

**Comment by ziogaschr** [comment]
Just did a PR https://github.com/jedisct1/swift-sodium/pull/2

**Comment by stannie** [comment]
Thanks guys
